### ISSUE TITLE
Enforce HTTPS

### ISSUE THREAD

**Issue by sourishg** [castacks/castacks.github.io#35]
HTTPS works fine if you explicitly type it in the URL. Ideally, the website should always enforce and redirect to HTTPS. Currently, GitHub is not allowing that in the settings of `castacks.github.io`. We should look into this and also remove any trace of HTTP from the source code.

Reference: https://help.github.com/en/github/working-with-github-pages/securing-your-github-pages-site-with-https

**Comment by bradygm** [comment]
This has now been fixed
