### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by bradygm** [castacks/castacks.github.io#50]
Address accessibility issues: https://wave.webaim.org/report#/https://theairlab.org/

**Comment by smash0190** [comment]
Can somebody volunteer for this?

**Comment by jfkeller** [comment]
I added a language tag that was missing in this commit 09120b0.

I think the rest of the issues WAVE reports are ok to ignore. Most of the are the following:
- No text on some links, but these have images instead, for example the twitter icon link at the bottom of the page.
- Alt text on images is the same as the title of the articles they link to. I think this is fine.
- Some text looks like a heading but isn't using a heading tag. The text still looks ok.
- It thinks some of the buttons on the Publications don't have text but they actually do.

**Comment by bradygm** [comment]
Commit 124ab8cc8659c4249c369994f889fd1b32fbc086 fixed most of the errors. Now we just have occasional warnings, as mentioned in the above comment by John. We could periodically revisit this and check the website.
