### ISSUE TITLE
Lazy load YouTube embeds with facades

### ISSUE THREAD

**Issue by bradygm** [castacks/castacks.github.io#53]
https://github.com/justinribeiro/lite-youtube

**Comment by bradygm** [comment]
Or https://github.com/paulirish/lite-youtube-embed#readme

**Comment by smash0190** [comment]
What is this for? For the research pages?

**Comment by bradygm** [comment]
This is mainly for our seminar pages where we have dozens of <iframe> elements which cause the load time to be rather long.

**Comment by bradygm** [comment]
https://pagespeed.web.dev/analysis/https-theairlab-org-tartanplanningseries/c3m0zcst31?form_factor=desktop

![image](https://github.com/castacks/castacks.github.io/assets/29281514/a4070d51-b784-4fe0-a271-bfeec9487aa7)

**Comment by bradygm** [comment]
Added the lazy load ability and updated the links on the Tartan Planning Series page (commits 63215ef and ea625e5). Improved the performance a lot. 

![image](https://github.com/castacks/castacks.github.io/assets/29281514/71b8814a-a929-41ba-b663-6938d04816c9)

All that is left is updating all of the iframe elements in the other series pages.

**Comment by bradygm** [comment]
Updated on all our seminar pages 953664af31da681558e7b268f5059504231f8055
