### ISSUE TITLE
Fix the news feed tab

### ISSUE THREAD

**Issue by bradygm** [castacks/castacks.github.io#64]

**Comment by bradygm** [comment]
https://www.wpbeginner.com/wp-tutorials/how-to-embed-medium-article-posts-on-wordpress/

**Comment by smash0190** [comment]
What should we do with this?

**Comment by jfkeller** [comment]
I added medium posts to the news feed in this commit de69ad3. Twitter has removed the ability to have embedded timelines that live update https://devcommunity.x.com/t/embedded-timelines-update-parameters-support/177112
