### ISSUE TITLE
Rendering of publications has some errors

### ISSUE THREAD

**Issue by smash0190** [castacks/castacks.github.io#85]
- @misc types don't render correctly (see patent examples)
- Other publications have extra commas in text.

**Comment by bradygm** [comment]
I think this is related to #39 which John worked on. Some things might be fixable, but some would have to be directly changed in the package we use (https://github.com/inukshuk/jekyll-scholar)

**Comment by bradygm** [comment]
@smash0190 could you add an example of the extra commas?

**Comment by bradygm** [comment]
Fixed by @jfkeller in #cf4623d6b2fc3e9c3b09cb70cca0becdf804fde6
